namespace: metro-prod

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

images:
  - name: metro-timetable
    newName: ghcr.io/kejhy93/metro-timetable
    newTag: latest

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
