spring.application.name=metro-timetable

pid.client.path=https://data.pid.cz/PID_GTFS.zip
pid.client.days.offset=7

pid.client.routes.ids=L991
#pid.client.routes.ids=L991,L992,L993

# Prometheus
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.create.cache: true
management.metrics.distribution.percentiles-histogram.create.releationship: true
management.metrics.distribution.percentiles-histogram.file.parse: true

