apiVersion: v1
kind: Service
metadata:
  name: metro-timetable
  labels:
    app: metro-timetable
spec:
  selector:
    app: metro-timetable
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort
