{
 "title": "Metro Timetable",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heap Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "Used - {{id}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\"}",
     "legendFormat": "commited - {{id}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Parse timetable", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Timetable Parse p95 Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(create_cache_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Create Cache"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(file_parse_seconds_bucket[$__rate_interval])))",
     "legendFormat": "File parse"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(create_releationship_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Create relationship"
    }
   ]
  },
  {
   "title": "Timetable Parse p99 Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(create_cache_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Create Cache"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(file_parse_seconds_bucket[$__rate_interval])))",
     "legendFormat": "File parse"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(create_releationship_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Create relationship"
    }
   ]
  },
  {
   "title": "Timetable Parse Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(create_cache_seconds_max[$__rate_interval]))\n/\n(rate(create_cache_seconds_count[$__rate_interval]))",
     "legendFormat": "Create Cache"
    },
    {
     "expr": "(rate(file_parse_seconds_max[$__rate_interval]))\n/\n(rate(file_parse_seconds_count[$__rate_interval]))",
     "legendFormat": "File parse"
    },
    {
     "expr": "(rate(create_releationship_seconds_max[$__rate_interval]))\n/\n(rate(create_releationship_seconds_count[$__rate_interval]))",
     "legendFormat": "Create relationship"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Rate (req/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Average response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(http_server_requests_seconds_sum[$__rate_interval]))\n/\n(rate(http_server_requests_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap Memory Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Heap Commited Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Heap Max  Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\"}",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  }
 ]
}