apiVersion: v1
kind: ConfigMap
metadata:
  name: metro-timetable-config
  labels:
    app: metro-timetable
data:
  PID_CLIENT_PATH: "https://data.pid.cz/PID_GTFS.zip"
  PID_CLIENT_DAYS_OFFSET: "7"
  PID_CLIENT_ROUTES_IDS: "L991,L992,L993"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health"
  SPRING_PROFILES_ACTIVE: "dev"
